Repository Daelso/Warhammer-IS12, pull requests merged in 2021-06, with the labels that each got.

#84 more improvements to the first map
  maps/warhammer/warhammer-2.dmm
Labels: enhancement, mapping

#86 Ready up style
  code/controllers/subsystems/jobs.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job_controller.dm
  maps/delta/jobs/astarte.dm
  maps/delta/jobs/guardsmen.dm
  maps/delta/jobs/pilgrims.dm
  maps/delta/jobs/warhammer_jobs.dm
  maps/warhammer/jobs/astarte.dm
  maps/warhammer/jobs/guardsmen.dm
  maps/warhammer/jobs/pilgrims.dm
  maps/warhammer/jobs/warhammer_jobs.dm
Labels: coding, enhancement

#89 updates movement speed on snow, mud, dirt
  code/game/gamemodes/warfare/turfs.dm
  code/game/turfs/flooring/flooring_premade.dm
Labels: coding, enhancement

#91 Skills based on jobs fix
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
Labels: coding, enhancement

#94 disable antags
  code/modules/client/preference_setup/preference_setup.dm
Labels: coding, enhancement

#98 Village medical + QoLs
  maps/delta/warhammer-2.dmm
  maps/delta/warhammer-3.dmm
Labels: mapping-delta

#99 nerf waaagh
  code/modules/mob/living/carbon/human/species/races/orks/abilities.dm
Labels: coding

#108 Change breacher armor into FW armor by Zion
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
Labels: coding, enhancement, spriting

#110 Wall sprite fixes
  icons/turf/wall.dmi
Labels: spriting

#109 Ork Fixes
  code/modules/mob/living/carbon/human/species/races/orks/ork_species.dm
  maps/delta/warhammer_items.dm
Labels: coding
